# -*- coding: utf-8 -*-
"""plot1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17bTt3XUafhRU1Xkht0vU5QFhxRKPJSYx

step 1: Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt

"""Step 2: Load the dataset and apply filter"""

data = pd.read_csv("/content/household_power_consumption.txt",
                   sep=";",
                   na_values=["?"],
                   parse_dates={'DateTime': ['Date', 'Time']},
                   keep_date_col=True,
                   dayfirst=True)
data = data[(data['DateTime'] >= '2007-02-01') & (data['DateTime'] <= '2007-02-02')]

"""Step 3: Make a plot"""

plt.hist(data['Global_active_power'],
         bins=10,
         color='blue')
plt.xlabel('Global Active Power (kilowatts)')
plt.ylabel('Frequency')
plt.title('Global Active Power')