# -*- coding: utf-8 -*-
"""plot2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJhDm9nRmNV6s269oNxw6YL2iLlmNyep
"""

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

data = pd.read_csv("/content/household_power_consumption.txt",
                   sep=";",
                   na_values=["?"],
                   parse_dates={'DateTime': ['Date', 'Time']},
                   keep_date_col=True,
                   dayfirst=True)
data = data[(data['DateTime'] >= '2007-02-01') & (data['DateTime'] <= '2007-02-02')]

data['datetime'] = pd.to_datetime(data['DateTime'], format='%d/%m/%Y %H:%M:%S')
print(data)

plt.plot(data['datetime'], data['Global_active_power'])
plt.xlabel('Date and Time')
plt.ylabel('Global Active Power (kilowatts)')
plt.title('Global Active Power')
plt.show()