# -*- coding: utf-8 -*-
"""plot 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191C7VDFkGu348Pe2CYtfo-v0TKwEU9C5
"""

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

data = pd.read_csv("/content/household_power_consumption.txt",
                   sep=";",
                   na_values=["?"],
                   parse_dates={'DateTime': ['Date', 'Time']},
                   keep_date_col=True,
                   dayfirst=True)
data = data[(data['DateTime'] >= '2007-02-01') & (data['DateTime'] <= '2007-02-02')]

data['datetime'] = pd.to_datetime(data['DateTime'], format='%d/%m/%Y %H:%M:%S')

plt.figure(figsize=(12, 12))

# Plot 1: Top Left
plt.subplot(2, 2, 1)
plt.plot(data['datetime'], data['Global_active_power'])
plt.ylabel('Global Active Power (kilowatts)')
plt.xlabel('Date and Time')

# Plot 2: Top Right
plt.subplot(2, 2, 2)
plt.plot(data['datetime'], data['Voltage'])
plt.ylabel('Voltage')
plt.xlabel('Date and Time')

# Plot 3: Bottom Left
plt.subplot(2, 2, 3)
plt.plot(data['datetime'], data['Sub_metering_1'], label='Sub_metering_1', color='black')
plt.plot(data['datetime'], data['Sub_metering_2'], label='Sub_metering_2', color='red')
plt.plot(data['datetime'], data['Sub_metering_3'], label='Sub_metering_3', color='blue')
plt.ylabel('Energy sub metering')
plt.xlabel('Date and Time')
plt.legend(loc='upper right')

# Plot 4: Bottom Right
plt.subplot(2, 2, 4)
plt.plot(data['datetime'], data['Global_reactive_power'])
plt.ylabel('Global Reactive Power')
plt.xlabel('Date and Time')

